name: github pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install .NET WebAssembly Tools
        run: dotnet workload install wasm-tools

      # Publish the site
      - name: Publish
        run: dotnet publish LoumTechnologiesWebsite.sln -c:Release -o:publish -p:GHPages=true

      - uses: actions/upload-pages-artifact@v1
        with:
          path: publish/wwwroot

      # Deploy the site
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          artifact_name: gh-pages
